name: human_typing_guard
description: A Flutter package that detects human typing patterns to prevent bots using speed, variability, cadence, and entropy analysis.
version: 1.0.0
homepage: https://github.com/your-username/flutter-human-typing-guard
repository: https://github.com/your-username/flutter-human-typing-guard
issue_tracker: https://github.com/your-username/flutter-human-typing-guard/issues
documentation: https://pub.dev/documentation/human_typing_guard/latest/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  http: ^1.1.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

topics:
  - security
  - anti-bot
  - heuristics
  - flutter
  - typing
  - analytics

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
